### ISSUE TITLE
Weather boost modifies baseDamage instead of basePower

### ISSUE THREAD

**Issue by sobolews** [augmt/gen6-damage-calc#2]
Power boosts from weather (such as a fire move in sun) should boost the basePower, not the baseDamage.

e.g.
0 Atk Vaporeon Flame Wheel vs. 0 HP / 0 Def Leafeon in Sun: 76-90 (28 - 33.2%) -- guaranteed 4HKO
(76, 76, 78, 78, 80, 80, 80, 82, 82, 84, 84, 86, 86, 88, 88, 90)

The maximum damage in gen6 is 88.

**Comment by augmt** [comment]
Thanks! The [rabbit hole](http://www.smogon.com/bw/articles/bw_complete_damage_formula) is deeper than I thought.
